services:
  a1111:
    build:
      context: ./services/forge
      dockerfile: Dockerfile
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    stop_signal: SIGKILL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute, utility]
